export const AVAILABLE_FEATURES = [
  { id: 'COMPLETE_ACCOUNTING', label: 'Complete Accounting Suite', category: 'Core ERP' },
  { id: 'INVENTORY_TRACKING', label: 'Advanced Stock & Inventory Management', category: 'Inventory' },
  { id: 'AUTO_LEDGER', label: 'Customer & Supplier Auto-Ledgers', category: 'Core ERP' },
  { id: 'WALLET_SYNC', label: 'Multi-Account Cash & Bank Sync', category: 'Financials' },
  { id: 'E2E_ENCRYPTION', label: 'Military-Grade End-to-End Encryption', category: 'Security' },
  { id: 'MULTI_USER_ROLES', label: 'Role-Based Multi-User Access', category: 'Security' },
  { id: 'CUSTOM_BRANDING', label: 'Custom Logo & Invoice Branding', category: 'Branding' },
  { id: 'CUSTOM_LOGO', label: 'Profile Business Logo Upload', category: 'Branding' },
  { id: 'ONLINE_STOREFRONT', label: 'Online Storefront & Website Builder', category: 'Website & Store' },
  { id: 'ADVANCED_REPORTS', label: 'Advanced P&L & Daybook Reports', category: 'Analytics' },
  { id: 'POS_BILLING', label: 'POS Quick Billing & Counter Mode (Premium)', category: 'Sales & POS' },
  { id: 'BARCODE_PRINTING', label: 'Print Barcode & Price Tag Stickers (Premium)', category: 'Sales & POS' },
  { id: 'STAFF_PAYROLL', label: 'Staff Attendance, Shifts & Salary Payroll (Premium)', category: 'HR & Payroll' },
  { id: 'PRIORITY_SUPPORT', label: 'Priority 24/7 Technical Support', category: 'Support' },
];
