export const AVAILABLE_FEATURES = [
  { id: 'COMPLETE_ACCOUNTING', label: 'Complete Accounting Suite', category: 'Core ERP' },
  { id: 'INVENTORY_TRACKING', label: 'Advanced Stock & Inventory Management', category: 'Inventory' },
  { id: 'AUTO_LEDGER', label: 'Customer & Supplier Auto-Ledgers', category: 'Core ERP' },
  { id: 'WALLET_SYNC', label: 'Multi-Account Cash & Bank Sync', category: 'Financials' },
  { id: 'E2E_ENCRYPTION', label: 'Military-Grade End-to-End Encryption', category: 'Security' },
  { id: 'MULTI_USER_ROLES', label: 'Role-Based Multi-User Access', category: 'Security' },
  { id: 'CUSTOM_BRANDING', label: 'Custom Logo & Invoice Branding', category: 'Branding' },
  { id: 'CUSTOM_LOGO', label: 'Profile Business Logo Upload', category: 'Branding' },
  { id: 'ONLINE_STOREFRONT', label: 'Online Storefront & Website Builder', category: 'Website & Store' },
  { id: 'ADVANCED_REPORTS', label: 'Advanced P&L & Daybook Reports', category: 'Analytics' },
  { id: 'POS_BILLING', label: 'BizManage POS Quick Billing & Counter Mode', category: 'Sales & POS' },
  { id: 'BARCODE_PRINTING', label: 'Custom Label & Barcode Sticker Printing', category: 'Sales & POS' },
  { id: 'GODOWN_MANAGEMENT', label: 'Manage Godowns & Warehouse Stock Transfer', category: 'Inventory' },
  { id: 'MANUFACTURING', label: 'Manufacturing & Bill of Materials (BOM)', category: 'Manufacturing' },
  { id: 'WHATSAPP_MARKETING', label: 'Unlimited WhatsApp Invoicing & Bulk Marketing', category: 'Marketing' },
  { id: 'TALLY_EXPORT', label: 'Export Data to Tally ERP 9 / Tally Prime', category: 'Integrations' },
  { id: 'PREMIUM_REPORTS', label: 'Balance Sheet, Billwise & Partywise P&L Reports', category: 'Analytics' },
  { id: 'STAFF_PAYROLL', label: 'Staff Attendance, Shifts & Salary Payroll', category: 'HR & Payroll' },
  { id: 'PRIORITY_SUPPORT', label: 'Priority 24/7 Technical Support', category: 'Support' },
];
